### ISSUE TITLE
Operator negation in AQL - part 2: negation without existence assumption

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/graphANNIS#187]
This enhancement extends #186 , negation with existence assumption, and should probably be implemented after that issue is closed.

Often, we want a negative search to confirm that some element does not interact with our data in some way. This element doesn't have to exist: we just want to make sure it is not there (i.e. nothing, the empty set is fine as fulfilling the place of #n). This probably requires a "where not exists..." clause in the SQL generation. 

It will be necessary to mark potentially non-existent elements in AQL. This will be done by *suffixing* a ? to the search expression. Here are some examples: suppose we want to find all NPs not dominated by a PP. It is **not** the case that a PP needs to be found and then checked for dominance of the NP. We simply want to go over everyone who dominates the NP (if at all) and make sure that none of them are PPs. We therefore explicitly state that we are not really searching for the PP. Note that the PP **cannot be bound** to the positive nodes in the query (those without ?) - otherwise its existence is implied and the solution in  #186 applies. Here is the query:

```
cat="NP" & cat="PP"? & #2 !> #1
```

This finds all NPs, then checks whether a cat="PP" exists which dominates them. If so, they are removed from the result set.

In the context of this issue, only simple annotation searches are valid as operands of the negated operator. It is not possible to connect two optional elements with a negated or non-negated operators. More complex structures would be introduced by #199 .

**Comment by thomaskrause** [comment]
@amir-zeldes I'm almost finished implementing this  in PR #200, but I changed the syntax from a suffix `?` to a postfix `?` (optional nodes were marked with `?tok` and is now marked with `tok?`. Is there a specific reason why we decided on prefix-`?` previously?. 

The motivation to change this is:
- to allow an AQL parser to differentiate the context in case we will use the `?` operator e.g. for optional terms (regex-style)
- to be more comparable to the regular expression operator. It is always confusing when special characters from regex behave differently in AQL (like `.`) and having the `?` at the front would be more confusing in my opinion.

**Comment by amir-zeldes** [comment]
Wow, this is amazing!!

The notation seems OK to me - the only disadvantage is the graphical dissimilarity of the case with key=val vs. just key, since "?" is sometimes adjacent to the key name and sometimes not:

key?
key="val"?

But I agree with your reasoning. Also note that #199 still has an example of the prefix notation.

Fantastic work implementing this, I really want to switch to ANNIS4 now!
