### ISSUE TITLE
export to graphml should trim visualizer configuration

### ISSUE THREAD

**Issue by MartinKl** [korpling/graphANNIS#222]
Consider the following fragment of a resolver_vis_map.annis:
```
[...] htmldoc	edition	hidden	4	hide_tok:true;annos:[...]; config: edition
```

When this corpus is imported with graphANNIS and then exported to graphml, the following fragment is created:
```
[...]
[visualizers.mappings]
" config" = ' edition'
[...]
```
As a consequence, the visualizer does not work when re-importing the graphml corpus.

**Comment by MartinKl** [comment]
I have to correct myself. The problem already occurs, when importing the corpus with graphANNIS. The problem is thus much more trivial and originates from the leading spaces in resolver_vis_map.annis. The question is, whether this should be considered a valid use of the map since it serves readability (which means import would have to trim it) or if such spaces should be forbidden. @thomaskrause ?

**Comment by thomaskrause** [comment]
I think this is an easy enough bug to fix on the graphANNIS side.  Especially when reading relANNIS files, we must mimic the old behavior and there *both* the name and the value where trimmed

 https://github.com/korpling/ANNIS/blob/74296161630d0acd2a166ad4edd63ebde13c7f34/annis-service/src/main/java/annis/dao/ResolverDaoHelper.java#L155

Even if we think that trimming the value might be a little bit weird, this would be the backward-compatible way of importing these files.
