### ISSUE TITLE
REST service and CLI tool should remove db.lock on exit

### ISSUE THREAD

**Issue by dlukes** [korpling/graphANNIS#230]
I typically run the two as different users (the REST service as a special system user `annis`, the CLI tool as myself), but both need to act on the same data directory. However, when the `db.lock` file is owned by a different user, running either of the binaries fails with a permission denied error while creating the lock, and it has to be removed manually. So I'm thinking it might be a good idea for both binaries to remove the lock on exit?

**Comment by thomaskrause** [comment]
Yes, I think this is a good idea. The implementation might be dependent on that the program does not crash, but I think this is negligible since graphANNIS would also start with the lock file present.
