### ISSUE TITLE
^ operator does not work with layer

### ISSUE THREAD

**Issue by amyisard** [korpling/graphANNIS#238]
**Describe the bug**

Queries with .layer work but with ^layer do not.

The query Gloss=‎/GLEICH.*‎/ .Gloss Gloss works as expected:

<img width="1866" alt="QueryDotOperator" src="https://user-images.githubusercontent.com/29375459/168842207-6f399b76-aeb5-4cfb-b972-02601e113fbe.png">

The query  Gloss=‎/GLEICH.*‎/ ^Gloss Gloss does not return any matches:

<img width="1866" alt="QueryHatOperator" src="https://user-images.githubusercontent.com/29375459/168843014-dacb81c4-5f74-458c-9290-b7d0d7209e08.png">

**Desktop:**
 - Operating System: iOS
 - Browser: chrome 101.0.4951.54
 - ANNIS Version 4.6.6 and 4.6.7

**Additional context**
The corpus was converted using pepper and imported in the relAnnis format.

**Comment by thomaskrause** [comment]
Thanks for reporting this bug! I could reproduce it with one of the default test corpora with segmentations and will fix this in the next release.
