### ISSUE TITLE
graphAnnis commands for deletion and renaming of a corpus

### ISSUE THREAD

**Issue by gcelano** [korpling/graphANNIS#296]
I use the interactive command-line, and I am wondering which commands allow deletion and rename of a corpus (I could not find them here: https://korpling.github.io/graphANNIS/docs/v3/cli.html)

**Comment by thomaskrause** [comment]
You can delete a corpus with the `delete <corpus name` command. You can not rename it, but you can choose to overwrite the corpus name during import by adding an additional parameter: `import <path> <corpusname>`.

I added these features to the documentation and they will be updated on the next release.

**Comment by gcelano** [comment]
I used `import <path> <corpusname>` via the CLI, but it does not work (also using graphannis 3.3.1). The corpus name specified is simply ignored.
